name: systemd unitfile service testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant

      - name: install service
        run: |
          sudo mkdir -p /usr/lib/systemd/user
          sudo cp service /usr/lib/systemd/user/docker-userlevel.service

      - name: run test
        run: systemd-analyze --user verify docker-userlevel.service
